// Code generated by MockGen. DO NOT EDIT.
// Source: user_repo.go

// Package userrepository is a generated GoMock package.
package userrepository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	user "github.com/codepnw/go-starter-kit/internal/features/user"
	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CheckEmailExists mocks base method.
func (m *MockUserRepository) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEmailExists", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckEmailExists indicates an expected call of CheckEmailExists.
func (mr *MockUserRepositoryMockRecorder) CheckEmailExists(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmailExists", reflect.TypeOf((*MockUserRepository)(nil).CheckEmailExists), ctx, email)
}

// FindUserByEmail mocks base method.
func (m *MockUserRepository) FindUserByEmail(ctx context.Context, email string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", ctx, email)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockUserRepositoryMockRecorder) FindUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindUserByEmail), ctx, email)
}

// InsertRefreshTokenTx mocks base method.
func (m *MockUserRepository) InsertRefreshTokenTx(ctx context.Context, tx *sql.Tx, token *user.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRefreshTokenTx", ctx, tx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRefreshTokenTx indicates an expected call of InsertRefreshTokenTx.
func (mr *MockUserRepositoryMockRecorder) InsertRefreshTokenTx(ctx, tx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRefreshTokenTx", reflect.TypeOf((*MockUserRepository)(nil).InsertRefreshTokenTx), ctx, tx, token)
}

// InsertUserTx mocks base method.
func (m *MockUserRepository) InsertUserTx(ctx context.Context, tx *sql.Tx, u *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUserTx", ctx, tx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUserTx indicates an expected call of InsertUserTx.
func (mr *MockUserRepositoryMockRecorder) InsertUserTx(ctx, tx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUserTx", reflect.TypeOf((*MockUserRepository)(nil).InsertUserTx), ctx, tx, u)
}
