// Code generated by MockGen. DO NOT EDIT.
// Source: jwt.go

// Package jwtToken is a generated GoMock package.
package jwttoken

import (
	reflect "reflect"

	user "github.com/codepnw/go-starter-kit/internal/features/user"
	gomock "github.com/golang/mock/gomock"
)

// MockJWTToken is a mock of JWTToken interface.
type MockJWTToken struct {
	ctrl     *gomock.Controller
	recorder *MockJWTTokenMockRecorder
}

// MockJWTTokenMockRecorder is the mock recorder for MockJWTToken.
type MockJWTTokenMockRecorder struct {
	mock *MockJWTToken
}

// NewMockJWTToken creates a new mock instance.
func NewMockJWTToken(ctrl *gomock.Controller) *MockJWTToken {
	mock := &MockJWTToken{ctrl: ctrl}
	mock.recorder = &MockJWTTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTToken) EXPECT() *MockJWTTokenMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockJWTToken) GenerateAccessToken(u *user.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", u)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockJWTTokenMockRecorder) GenerateAccessToken(u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockJWTToken)(nil).GenerateAccessToken), u)
}

// GenerateRefreshToken mocks base method.
func (m *MockJWTToken) GenerateRefreshToken(u *user.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", u)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockJWTTokenMockRecorder) GenerateRefreshToken(u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockJWTToken)(nil).GenerateRefreshToken), u)
}

// VerifyAccessToken mocks base method.
func (m *MockJWTToken) VerifyAccessToken(tokenStr string) (*UserClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAccessToken", tokenStr)
	ret0, _ := ret[0].(*UserClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAccessToken indicates an expected call of VerifyAccessToken.
func (mr *MockJWTTokenMockRecorder) VerifyAccessToken(tokenStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAccessToken", reflect.TypeOf((*MockJWTToken)(nil).VerifyAccessToken), tokenStr)
}

// VerifyRefreshToken mocks base method.
func (m *MockJWTToken) VerifyRefreshToken(tokenStr string) (*UserClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRefreshToken", tokenStr)
	ret0, _ := ret[0].(*UserClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRefreshToken indicates an expected call of VerifyRefreshToken.
func (mr *MockJWTTokenMockRecorder) VerifyRefreshToken(tokenStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRefreshToken", reflect.TypeOf((*MockJWTToken)(nil).VerifyRefreshToken), tokenStr)
}
